[package]
name = "ayaka-check"
version = "0.1.0"
edition = "2021"

[dependencies]
ayaka-runtime = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
clap = { workspace = true, features = ["derive"] }
flexi_logger = { workspace = true }
