[package]
name = "gal-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
gal-script = { path = "../gal-script" }
gal-primitive = { path = "../gal-primitive" }
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }

[dev-dependencies]
lazy_static = "1.4"
