version: 2
updates:
- package-ecosystem: cargo
  directory: "/utils"
  schedule:
    interval: weekly

- package-ecosystem: cargo
  directory: "/plugins"
  schedule:
    interval: weekly

- package-ecosystem: cargo
  directory: "/bins"
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: "/bins/ayaka-gui"
  schedule:
    interval: weekly
