trigger:
  branches:
    include:
      - master

jobs:
- job: Build
  strategy:
    matrix:
      win-x64:
        platform: 'win'
        target: 'x86_64-pc-windows-msvc'
        image: 'windows-latest'
      linux-x64:
        platform: 'linux'
        target: 'x86_64-unknown-linux-gnu'
        image: 'ubuntu-22.04'
      macos-x64:
        platform: 'mac'
        target: 'x86_64-apple-darwin'
        image: 'macOS-latest'
  pool:
    vmImage: $(image)
  
  steps:
  - script: |
      sudo apt update
      sudo apt install libwebkit2gtk-4.0-dev libicu-dev
    condition: eq(variables.platform, 'linux')
    displayName: "Install dependencies on Linux"

  - pwsh: rustup target add wasm32-wasi
    displayName: "Install WASM32 target"

  - pwsh: make plugins
    displayName: "Build plugins"

  - pwsh: make release
    displayName: "Build CLI"

  - pwsh: make release-gui
    displayName: "Build GUI"

  - pwsh: make release-latex
    displayName: "Build LaTeX compiler"
