[workspace]
members = [
    "gal-script",
    "gal-primitive",
    "gal-runtime",
    "gal",
    "gal-protocol",
    "plugins/format",
]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
