[package]
name = "gal-bindings"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"

[dependencies]
fp-bindgen = "1.0"
fp-bindgen-support = { version = "1.0", features = ["async", "guest"] }
serde = "1.0"

[dev-dependencies]
serde_yaml = "0.8"
