[package]
name = "gal-bindings"
version = "0.1.0"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git" }

[dev-dependencies]
serde_yaml = "0.8"
