[package]
name = "ayaka-primitive"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = "2.0"
regex = "1"

[dev-dependencies]
serde_yaml = "0.9"
