[package]
name = "ayaka-primitive"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
regex = "1"

[dev-dependencies]
serde_yaml = { workspace = true }
