[package]
name = "ayaka-script"
version = "0.1.0"
edition = "2021"

[dependencies]
ayaka-script-types = { path = "../ayaka-script-types" }
lalrpop-util = { version = "0.19", features = ["lexer"] }
regex = "1"
log = "0.4"

[build-dependencies]
lalrpop = "0.19"
