[package]
name = "ayaka-script"
version = "0.1.0"
edition = "2021"

[dependencies]
ayaka-primitive = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
trylog = { workspace = true }
lalrpop-util = { version = "0.19", features = ["lexer"] }

[build-dependencies]
lalrpop = "0.19"
