[package]
name = "gal-locale"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0"
rust_icu_uloc = { version = "2.0", default-features = false, features = ["renaming"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.38", features = [
    "alloc",
    "Win32_Globalization",
] }
