[package]
name = "progress-future"
version = "0.1.0"
edition = "2021"

[dependencies]
progress-future-impl = { path = "../progress-future-impl" }
tokio = "1"
tokio-stream = "0.1"
pin-project = "1.0"

[dev-dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["macros", "rt"] }
