[package]
name = "gal-primitive"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = { version = "0.4", features = ["std"] }

[dev-dependencies]
serde_yaml = "0.8"
