title: Live2D
author: Berrysoft
props:
  ch_models: ch_models
  ch_names: Haru,Hiyori,Mao
  ch_Haru_scale: 0.25
  ch_Hiyori_scale: 0.2
  ch_Mao_scale: 0.1
res: res
plugins:
  dir: plugins
  modules:
    - live2d
base_lang: ja
paras: paras
start: show
