title: Live2D
author: Berrysoft
props:
  ch_models: ch_models
res:
  ja:
    ch_Haru: はる
    ch_Hiyori: ひより
    ch_Mao: まお
plugins:
  dir: ../plugins/
  modules:
    - live2d
base_lang: ja
paras:
  ja:
    -
      tag: show
      texts:
        - /Haru//おはよう
        - /Hiyori//~~~ヾ(＾∇＾)おはよー♪
        - /Mao//お早う
