[package]
name = "ayaka-gui"
version = "0.1.0"
edition = "2021"

[build-dependencies]
# TODO: remove this
# Avoid 0.13.3, because we use workspace dependencies.
cargo_toml = "=0.13.2"
tauri-build = { version = "1.2", features = [] }

[dependencies]
ayaka-model = { workspace = true }
flexi_logger = { workspace = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["cli", "window-all"] }
tauri-plugin-window-state = "0.1"
tryiterator = { git = "https://github.com/Pernosco/tryiterator.git" }
axum = { version = "0.6", default-features = false, features = ["http1", "tokio"] }
tower-http = { version = "0.3", features = ["cors", "trace"] }
mime_guess = "2.0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
