[package]
name = "ayaka-gui"
description = "GUI frontend for Ayaka."
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "ayaka_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-alpha.2", features = [] }

[dependencies]
ayaka-model = { workspace = true }
flexi_logger = { workspace = true }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-alpha.4", features = ["cli", "dialog-open", "window-all"] }
axum = { version = "0.6", default-features = false, features = [
    "http1",
    "tokio",
    "headers",
] }
tower-http = { version = "0.4", features = ["cors", "trace"] }
mime_guess = "2.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace.git", branch = "next" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
