[package]
name = "ayaka-gui"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.0", features = [] }

[dependencies]
ayaka-runtime = { path = "../../../utils/ayaka-runtime" }
flexi_logger = { version = "0.24", default-features = false, features = ["colors"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["cli", "protocol-all", "window-all"] }
actix-web = "4"
actix-files = "0.6"
mime_guess = "2.0"
portpicker = "0.1"
trylog = "0.2"
