[package]
name = "ayaka-gui"
description = "GUI frontend for Ayaka."
version = "0.3.0"
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
categories = ["game-development"]
keywords = ["game", "engine", "galgame"]
license = "MIT"
repository = "https://github.com/Uni-Gal/Ayaka"

[lib]
name = "ayaka_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
ayaka-plugin-wasmi = { workspace = true }
ayaka-model = { workspace = true }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.0.0", features = [] }
tauri-plugin-os = "2.0.0"
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }
axum = { version = "0.7", default-features = false, features = [
    "http1",
    "tokio",
] }
axum-extra = { version = "0.9", features = ["typed-header"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }
headers = "0.4"
mime_guess = "2"
vfs-tar = { version = "0.5", features = ["mmap"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-dialog = "2.0.0"
tauri-plugin-window-state = "2.0.0"
flexi_logger = { workspace = true }

[target.'cfg(target_os = "ios")'.dependencies]
file-picker-ios = { git = "https://github.com/Berrysoft/file-picker-ios.git" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14"
file-picker-android = { git = "https://github.com/Berrysoft/file-picker-android.git" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
