title: Markdown
author: Berrysoft
plugins:
  dir: ../plugins/
  modules:
    - markdown
base_lang: en
paras:
  en:
    -
      tag: example
      texts:
        - '# HEAD'
        - Normal
        - '*Italic*'
        - '**Bold**'
        - '`code`'
        - Mixed normal *italic* **bold** `code`.