[workspace]
members = [
    "fallback",
    "locale",
    "progress-future",
    "gal-primitive",
    "gal-runtime",
    "gal-script",
]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
