[workspace]
members = [
    "ayaka-bindings-types",
    "ayaka-script",
    "ayaka-plugin",
    "ayaka-plugin-wasmer",
    "ayaka-plugin-wasmtime",
    "ayaka-runtime",
]

resolver = "2"

[profile.release]
lto = true
codegen-units = 1
