[package]
name = "gal-latex"
version = "0.1.0"
edition = "2021"

[dependencies]
gal-runtime = { path = "../../utils/gal-runtime" }
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt"] }
clap = { version = "3.1", features = ["derive"] }
env_logger = "0.9"
