[book]
authors = ["Berrysoft"]
language = "en"
multilingual = true
src = "src"
title = "Ayaka Book"

[rust]
edition = "2021"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[[output.i18n.translations]]
language = "zh-Hans"
title = "Ayaka Book"
