name: Book
on:
  push:
    branches: ["master"]
    paths:
      - 'book/**'
jobs:
  Book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Setup mdbook-graphviz
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook-graphviz
      - name: Build book
        run: make book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
