name: Release
on:
  push:
    branches: ["master"]
jobs:
  Build:
    strategy:
      matrix:
        platform:
          - name: linux-x64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - name: macos-x64
            os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y libwebkit2gtk-4.0-dev
        if: matrix.platform.name == 'linux-x64'
      - name: Install targets
        run: rustup target add ${{ matrix.platform.target }}
      - name: Build
        run: make release-cross TARGET=${{ matrix.platform.target }}
