name: Test
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libwebkit2gtk-4.0-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install targets
        run: |
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi
      - name: Test
        run: make test
        working-directory: .
