[package]
name = "ayaka-latex"
version = "0.1.0"
edition = "2021"

[dependencies]
ayaka-runtime = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "rt"] }
clap = { workspace = true, features = ["derive"] }
flexi_logger = { workspace = true }
